from rka.components.resources import Resource
from rka.components.resources import ResourceBundle


class OverseerTraitsBundle (ResourceBundle):
	def __init__(self, *args, **kwargs):
		ResourceBundle.__init__(self, *args, **kwargs)

	PATTERN_OVERSEER_TRAIT_ADVENTUROUS: Resource = None
	PATTERN_OVERSEER_TRAIT_AGILE: Resource = None
	PATTERN_OVERSEER_TRAIT_AMOROUS: Resource = None
	PATTERN_OVERSEER_TRAIT_CAUTIOUS: Resource = None
	PATTERN_OVERSEER_TRAIT_CHARMING: Resource = None
	PATTERN_OVERSEER_TRAIT_COMPASSIONATE: Resource = None
	PATTERN_OVERSEER_TRAIT_CORRUPT: Resource = None
	PATTERN_OVERSEER_TRAIT_COURAGEOUS: Resource = None
	PATTERN_OVERSEER_TRAIT_CUNNING: Resource = None
	PATTERN_OVERSEER_TRAIT_DARING: Resource = None
	PATTERN_OVERSEER_TRAIT_DEVOTED: Resource = None
	PATTERN_OVERSEER_TRAIT_DEXTEROUS: Resource = None
	PATTERN_OVERSEER_TRAIT_DIPLOMATIC: Resource = None
	PATTERN_OVERSEER_TRAIT_EXPLORATIVE: Resource = None
	PATTERN_OVERSEER_TRAIT_FOCUSED: Resource = None
	PATTERN_OVERSEER_TRAIT_FORAGER: Resource = None
	PATTERN_OVERSEER_TRAIT_FRIVOLITY: Resource = None
	PATTERN_OVERSEER_TRAIT_HONEST: Resource = None
	PATTERN_OVERSEER_TRAIT_IMMOLATING: Resource = None
	PATTERN_OVERSEER_TRAIT_IMPATIENT: Resource = None
	PATTERN_OVERSEER_TRAIT_INQUISITIVE: Resource = None
	PATTERN_OVERSEER_TRAIT_INTELLIGENT: Resource = None
	PATTERN_OVERSEER_TRAIT_LUCKY: Resource = None
	PATTERN_OVERSEER_TRAIT_LYCANTROPHY: Resource = None
	PATTERN_OVERSEER_TRAIT_MANIPULATIVE: Resource = None
	PATTERN_OVERSEER_TRAIT_NOBLE: Resource = None
	PATTERN_OVERSEER_TRAIT_PERSUASSIVE: Resource = None
	PATTERN_OVERSEER_TRAIT_RIGHTEOUS: Resource = None
	PATTERN_OVERSEER_TRAIT_SECRETIVE: Resource = None
	PATTERN_OVERSEER_TRAIT_SHREWD: Resource = None
	PATTERN_OVERSEER_TRAIT_SLY: Resource = None
	PATTERN_OVERSEER_TRAIT_STALWART: Resource = None
	PATTERN_OVERSEER_TRAIT_STRONG: Resource = None
	PATTERN_OVERSEER_TRAIT_TOUGH: Resource = None
	PATTERN_OVERSEER_TRAIT_UNFLAPPABLE: Resource = None
	PATTERN_OVERSEER_TRAIT_UNPREDICTABLE: Resource = None
	PATTERN_OVERSEER_TRAIT_VERDUROUS: Resource = None
	PATTERN_OVERSEER_TRAIT_VIGILANT: Resource = None
	PATTERN_OVERSEER_TRAIT_WISE: Resource = None
