from rka.components.io.log_service import LogLevel

LOG_COMMON = LogLevel.WARN
LOG_EVENTS = LogLevel.WARN
LOG_HOTKEYS = LogLevel.WARN
LOG_DISCOVERY = LogLevel.WARN
LOG_RPC = LogLevel.WARN
LOG_COMMANDS = LogLevel.WARN
LOG_APPCONTROL = LogLevel.WARN
LOG_RESOURCE_MGT = LogLevel.WARN
LOG_DATABASE = LogLevel.WARN

LOG_INPUT_EVENTS = LogLevel.WARN
LOG_VOICE_AUDIO = LogLevel.WARN
LOG_CAPTURING = LogLevel.WARN
LOG_INJECTIONS = LogLevel.WARN
LOG_NOTIFICATIONS = LogLevel.WARN
LOG_UI_OVERLAY = LogLevel.WARN

LOG_PARSING = LogLevel.WARN
LOG_TRIGGERS = LogLevel.WARN

LOG_CENSUS = LogLevel.WARN
LOG_GAME_STATE_OBJECTS = LogLevel.INFO
LOG_ABILITY_BUILDER = LogLevel.WARN
LOG_ABILITY = LogLevel.WARN
LOG_ABILITY_CASTING = LogLevel.INFO
LOG_EFFECT = LogLevel.INFO
LOG_PLAYER = LogLevel.WARN

LOG_REQUEST_PROCESSOR = LogLevel.WARN
LOG_REQUESTS = LogLevel.WARN
LOG_SPECIAL_REQUESTS = LogLevel.WARN

LOG_AUTOMATION = LogLevel.INFO
LOG_SCRIPTING_FRAMEWORK = LogLevel.DEBUG
LOG_COMBAT_SCRIPTING_FRAMEWORK = LogLevel.DEBUG
LOG_MOVEMENT = LogLevel.WARN
LOG_SCRIPTS = LogLevel.DEBUG
